

spring:
### config datasource - postgreSQL
  datasource:
    private:
      url: jdbc:postgresql://localhost:5430/his?currentSchema=webtool
      username: postgres
      password: 123zxc123
      sqlScriptEncoding: UTF-8
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: 15
        minimum-idle: 3
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
